# -*- coding: utf-8 -*-
"""bot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18CyxgQ5q2uDWZCVKrHVxlz7DNEl6eGOV
"""

import os
import time
import feedparser
from datetime import datetime, timedelta
import requests
from bs4 import BeautifulSoup

# إعدادات التليجرام
TELEGRAM_BOT_TOKEN = "8907902912:AAHhoLdD3xODWhqWOEUIBS9xf0_MqktSPw8"
TELEGRAM_CHAT_IDS = ["6616775420", "-1004335482676"]

# مصادر الأخبار ومتابعة المنصات
RSS_URLS = [
    # أخبار جوجل الرسمية لحزب العدل
    "https://news.google.com/rss/search?q=%D8%AD%D8%B2%D8%A8%20%D8%A7%D9%84%D8%B9%D8%AF%D9%84&hl=ar&gl=EG&ceid=EG:ar",
]

# صفحات فيسبوك أو روابط البحث المباشر للرصد
FACEBOOK_TARGETS = [
    # رابط النسخة العامة لفيسبوك للبحث عن حزب العدل أو صفحة معينة
    "https://mbasic.facebook.com/public/%D8%AD%D8%B2%D8%A8-%D8%A7%D9%84%D8%B9%D8%AF%D9%84"
]

SENT_NEWS_FILE = "sent_news.txt"

DEPUTIES_INFO = """
📡 **مينا رادار - دليل نواب حزب العدل (2025 - 2030)**

🔹 **أولاً: مجلس النواب (11 نائباً)**
1. عبد المنعم إمام (رئيس الحزب - التجمع الخامس)
2. محمد فؤاد
3. حسام حسن (الخشت)
4. حسين هريدي
5. أحمد ناصر
6. فاطمة عادل
7. مروة بوريص
8. صافيناز طلعت
9. هايدي المغازي
10. علي خليفة
11. سحر عتمان

🔹 **ثانياً: مجلس الشيوخ (5 نواب)**
1. إسماعيل الشرقاوي (نائب رئيس الحزب ورئيس الهيئة البرلمانية)
2. أشرف عبدالغني
3. أحمد سيد أحمد
4. محمد جامع
5. نيڤين فارس
"""

def send_telegram_message(text):
    if not TELEGRAM_BOT_TOKEN or not TELEGRAM_CHAT_IDS:
        print("Telegram tokens or chat IDs are missing!")
        return
    
    for chat_id in TELEGRAM_CHAT_IDS:
        url = f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}/sendMessage"
        payload = {
            "chat_id": chat_id,
            "text": text,
            "parse_mode": "Markdown"
        }
        try:
            response = requests.post(url, json=payload)
            response.raise_for_status()
            time.sleep(1)
        except Exception as e:
            print(f"Error sending message to Telegram (Chat ID: {chat_id}): {e}")

def check_telegram_commands():
    if not TELEGRAM_BOT_TOKEN:
        return
    url = f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}/getUpdates"
    try:
        response = requests.get(url).json()
        if "result" in response:
            for update in response["result"]:
                message = update.get("message", {})
                text = message.get("text", "").strip().lower()
                
                if text in ["/deputies", "/nawap", "النواب"]:
                    send_telegram_message(DEPUTIES_INFO)
    except Exception as e:
        print(f"Error checking telegram commands: {e}")

def load_sent_news():
    if os.path.exists(SENT_NEWS_FILE):
        with open(SENT_NEWS_FILE, "r", encoding="utf-8") as f:
            return set(line.strip() for line in f if line.strip())
    return set()

def save_sent_news(sent_set):
    with open(SENT_NEWS_FILE, "w", encoding="utf-8") as f:
        for link in sent_set:
            f.write(f"{link}\n")

def scrape_facebook_basic():
    """سحب المنشورات أو الروابط المباشرة من النسخة الخفيفة لفيسبوك بدون حظر"""
    posts = []
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
    }
    
    for url in FACEBOOK_TARGETS:
        try:
            response = requests.get(url, headers=headers, timeout=10)
            if response.status_code == 200:
                soup = BeautifulSoup(response.text, 'html.parser')
                # استخراج الروابط أو النصوص العامة من النسخة الأساسية الخفيفة
                for a in soup.find_all('a', href=True):
                    href = a['href']
                    text = a.get_text().strip()
                    # تصفية الروابط لتكون خاصة بالمنشورات أو الصفحات المتعلقة
                    if '/story.php' in href or 'posts' in href or 'permalink' in href:
                        if not href.startswith('http'):
                            href = "https://mbasic.facebook.com" + href
                        if text and len(text) > 15: # التأكد من وجود محتوى نصي ذو قيمة
                            posts.append({"title": text, "link": href})
        except Exception as e:
            print(f"Error scraping Facebook: {e}")
            
    return posts

def main():
    check_telegram_commands()

    sent_news = load_sent_news()
    new_links_added = False
    
    # 1. رصد أخبار جوجل RSS
    for rss_url in RSS_URLS:
        feed = feedparser.parse(rss_url)
        for entry in reversed(feed.entries):
            link = getattr(entry, "link", None)
            title = getattr(entry, "title", "خبر جديد")
            if not link or link in sent_news:
                continue
            
            message = f"📡 **مينا رادار - خبر جديد**\n\n📌 {title}\n🔗 {link}"
            send_telegram_message(message)
            sent_news.add(link)
            new_links_added = True

    # 2. رصد السوشيال ميديا ومباشرة من فيسبوك
    fb_posts = scrape_facebook_basic()
    for post in fb_posts:
        link = post["link"]
        title = post["title"]
        if link not in sent_news:
            message = f"📱 **مينا رادار - بوست فيسبوك**\n\n📌 {title}\n🔗 {link}"
            send_telegram_message(message)
            sent_news.add(link)
            new_links_added = True

    if new_links_added:
        save_sent_news(sent_news)

if __name__ == "__main__":
    main()
