# -*- coding: utf-8 -*-
"""bot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18CyxgQ5q2uDWZCVKrHVxlz7DNEl6eGOV
"""

import os
import time
import feedparser
from datetime import datetime, timedelta
import requests

# إعدادات التليجرام
TELEGRAM_BOT_TOKEN = "8907902912:AAHhoLdD3xODWhqWOEUIBS9xf0_MqktSPw8"
TELEGRAM_CHAT_IDS = ["6616775420", "-1004335482676"]

# مصادر البحث
RSS_URLS = [
    "https://news.google.com/rss/search?q=%D8%AD%D8%B2%D8%B8+%D8%A7%D9%84%D8%B9%D8%AF%D9%84&hl=ar&gl=EG&ceid=EG:ar",
    "https://news.google.com/rss/search?q=%D8%AD%D8%B2%D8%B8+%D8%A7%D9%84%D8%B9%D8%AF%D9%84+%D9%85%D8%B5%D8%B1&hl=ar&gl=EG&ceid=EG:ar"
]

SENT_NEWS_FILE = "sent_news.txt"

DEPUTIES_INFO = """
📡 **مينا رادار - دليل نواب حزب العدل (2025 - 2030)**

🔹 **أولاً: مجلس النواب (11 نائباً)**
1. عبد المنعم إمام (رئيس الحزب - التجمع الخامس)
2. محمد فؤاد
3. حسام حسن (الخشت)
4. حسين هريدي
5. أحمد ناصر
6. فاطمة عادل
7. مروة بوريص
8. صافيناز طلعت
9. هايدي المغازي
10. علي خليفة
11. سحر عتمان

🔹 **ثانياً: مجلس الشيوخ (5 نواب)**
1. إسماعيل الشرقاوي (نائب رئيس الحزب ورئيس الهيئة البرلمانية)
2. أشرف عبدالغني
3. أحمد سيد أحمد
4. محمد جامع
5. نيڤين فارس
"""

def send_telegram_message(text):
    if not TELEGRAM_BOT_TOKEN or not TELEGRAM_CHAT_IDS:
        print("Telegram tokens or chat IDs are missing!")
        return

    for chat_id in TELEGRAM_CHAT_IDS:
        url = f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}/sendMessage"
        payload = {
            "chat_id": chat_id,
            "text": text,
            "parse_mode": "Markdown"
        }
        try:
            response = requests.post(url, json=payload)
            response.raise_for_status()
            time.sleep(1) # فاصل زمني لتجنب حظر تليجرام (Too Many Requests)
        except Exception as e:
            print(f"Error sending message to Telegram (Chat ID: {chat_id}): {e}")

def check_telegram_commands():
    if not TELEGRAM_BOT_TOKEN:
        return
    url = f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}/getUpdates"
    try:
        response = requests.get(url).json()
        if "result" in response:
            for update in response["result"]:
                message = update.get("message", {})
                text = message.get("text", "").strip().lower()

                if text in ["/deputies", "/nawap", "النواب"]:
                    send_telegram_message(DEPUTIES_INFO)
    except Exception as e:
        print(f"Error checking telegram commands: {e}")

def load_sent_news():
    if os.path.exists(SENT_NEWS_FILE):
        with open(SENT_NEWS_FILE, "r", encoding="utf-8") as f:
            return set(line.strip() for line in f if line.strip())
    return set()

def save_sent_news(sent_set):
    with open(SENT_NEWS_FILE, "w", encoding="utf-8") as f:
        for link in sent_set:
            f.write(f"{link}\n")

def main():
    # فحص الأوامر الواردة (مثل طلب النواب)
    check_telegram_commands()

    sent_news = load_sent_news()
    new_links_added = False

    # تحديد نطاق آخر 24 ساعة بدقة
    now = datetime.now()
    time_limit = now - timedelta(hours=24)

    for rss_url in RSS_URLS:
        feed = feedparser.parse(rss_url)

        for entry in reversed(feed.entries):
            link = entry.link
            title = entry.title

            # قراءة تاريخ نشر الخبر
            published_parsed = getattr(entry, "published_parsed", None)
            if published_parsed:
                entry_date = datetime(*published_parsed[:6])

                # لو الخبر أقدم من 24 ساعة، نتجاهله تماماً (ونضيفه للقائمة كأنه أرسل لمنع تكرار فحصه)
                if entry_date < time_limit:
                    if link not in sent_news:
                        sent_news.add(link)
                        new_links_added = True
                    continue

            # لو الخبر جديد وداخل الـ 24 ساعة ولم يُرسل من قبل
            if link not in sent_news:
                message = f"📡 **مينا رادار - خبر جديد**\n\n📌 {title}\n🔗 {link}"
                send_telegram_message(message)
                sent_news.add(link)
                new_links_added = True

    if new_links_added:
        save_sent_news(sent_news)

if __name__ == "__main__":
    main()
