# -*- coding: utf-8 -*-
"""bot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18CyxgQ5q2uDWZCVKrHVxlz7DNEl6eGOV
"""

import os
import requests
import feedparser

TELEGRAM_BOT_TOKEN = "8907902912:AAHhoLdD3xODWhqWOEUIBS9xf0_MqktSPw8"
TELEGRAM_CHAT_IDS = ["6616775420", "-1004335482676"]

def send_telegram_message(message):
    for chat_id in TELEGRAM_CHAT_IDS:
        url = f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}/sendMessage"
        payload = {
            "chat_id": chat_id,
            "text": message,
            "parse_mode": "Markdown"
        }
        requests.post(url, json=payload)

SENT_FILE = "sent_news.txt"

def load_sent_links():
    if os.path.exists(SENT_FILE):
        with open(SENT_FILE, "r", encoding="utf-8") as f:
            return set(line.strip() for line in f)
    return set()

def save_sent_link(link):
    with open(SENT_FILE, "a", encoding="utf-8") as f:
        f.write(link + "\n")

def check_news():
    sent_links = load_sent_links()
    rss_url = "https://news.google.com/rss/search?q=حزب+العدل&hl=ar&gl=EG&ceid=EG:ar"
    feed = feedparser.parse(rss_url)

    for entry in feed.entries:
        if "حزب العدل" in entry.title and entry.link not in sent_links:
            alert_text = f"🚨 *تنبيه رصد جديد بواسطة مينا رادار*\n\n📌 *العنوان:* {entry.title}\n🔗 *الرابط:* {entry.link}"
            send_telegram_message(alert_text)
            save_sent_link(entry.link)

if __name__ == "__main__":
    check_news()
